### ISSUE TITLE
 touch keyboard and screen auto-rotate not working 

### ISSUE THREAD

**Issue by Iamloumie** [chinrw/stephan-raabe-dotfiles#1]
hi, stephan.. 
Thank you for the beautiful hyprland config  but the screen of HP X360 1030 g2 does not auto-rotate when its converted to tablet mode, the touch keyboard does not pop up while trying to type as well.. please stepan, help out with this...

**Comment by chinrw** [comment]
Hi, this project is forked from https://gitlab.com/stephan-raabe/dotfiles , you may need to open a issue there.  
As for tablet mode, I don't have such device, probably you could chceck with issue https://github.com/JeanSchoeller/iio-hyprland/pull/14 and use `hyprctl devices`
